# NumPy Arrays

In [ ]:
## one-d vectors
## two-d matrices

In [6]:
import numpy as np

In [7]:
my_list = [1,2,3]

In [8]:
first_np_arr = np.array(my_list)

In [9]:
first_np_arr

array([1, 2, 3])

In [15]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.zeros(2)

array([0., 0.])

In [36]:
#five random numbers between 0-1 in vector array 
np.random.rand(5)

array([0.67695409, 0.22204463, 0.15737184, 0.0939009 , 0.34159264])

In [37]:
#five by five random numbers between 0-1 in matrix array
np.random.rand(5,5)

array([[0.1998956 , 0.54223081, 0.25659166, 0.02231059, 0.95151107],
       [0.82493022, 0.81622149, 0.95583791, 0.28152141, 0.18582502],
       [0.58820239, 0.55494373, 0.1514309 , 0.23481076, 0.59258972],
       [0.96222316, 0.93923703, 0.16961167, 0.21482255, 0.4921816 ],
       [0.30816105, 0.83985295, 0.48909328, 0.35936208, 0.75017744]])

In [38]:
#random values of normal distribution in matrix array
np.random.randn(4,4)

array([[ 1.2261087 , -0.65682103, -0.34221362,  0.29025841],
       [-0.93090231,  0.72708491,  0.08666336,  0.02256094],
       [ 0.47994986, -0.43306262,  0.3347081 , -0.67022608],
       [-1.36876268, -0.5072055 , -0.73775919, -0.59354773]])

In [40]:
#10 random integers in a vector array
np.random.randint(1,10)

7

## Indexing

In [42]:
import numpy as np

In [52]:
arr = np.arange(1,11)

In [53]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
#indexing same as in regular python
arr[8]

9

In [55]:
arr[1:5]

array([2, 3, 4, 5])

In [56]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [57]:
arr[6:]

array([ 7,  8,  9, 10])

In [58]:
#numpy arrays can broadcast
arr[0:5] = 100

In [59]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])